version: '3.12'
services:
  frontend:
    build: streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./streamlit:/app
    restart: always
    networks:
      - app
    container_name: frontend

  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge